version: '3'

services:
  web:
    build:
      context: ./src
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    depends_on:
      - redis
    networks:
      - webnet
  redis:
    image: redis:alpine
    networks:
      - webnet

networks:
  webnet:
